name: Motor_Testing

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install PlatformIO
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Build the Project
      - name: Build Project
        working-directory: Motor-Testing
        run: platformio run
